# Generated by Django 4.2.5 on 2023-10-11 12:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cname",
                    models.CharField(max_length=30, unique=True, verbose_name="类别名称"),
                ),
            ],
            options={
                "verbose_name_plural": "类别",
                "db_table": "t_category",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tname",
                    models.CharField(max_length=20, unique=True, verbose_name="标签名称"),
                ),
            ],
            options={
                "verbose_name_plural": "标签",
                "db_table": "t_tag",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, unique=True, verbose_name="标题"),
                ),
                ("desc", models.CharField(max_length=200, verbose_name="简介")),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(verbose_name="内容"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("isdelete", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="post.category",
                        verbose_name="所属类别",
                    ),
                ),
                ("tag", models.ManyToManyField(to="post.tag", verbose_name="所属标签")),
            ],
            options={
                "verbose_name_plural": "帖子",
                "db_table": "t_post",
            },
        ),
    ]
